name: R

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'

jobs:
    unit-test-job:
      name: run test job
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - uses: r-lib/actions/setup-r@v2
          with:
              r-version: '4.2.2'
        - run: Rscript -e 'install.packages(c("png", "rmarkdown"), repos = "https://cran.ism.ac.jp/"); rmarkdown::render("Crypto.Rmd")'

