name: R

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'

jobs:
    unit-test-job:
      name: run unit-test job
      runs-on: macos-latest
      steps:
          uses: r-lib/actions/setup-r@v2
        - run: Rscript -e 'print("hello")'

