name: R

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'

jobs:
  unit-test-job:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: '4.2.2'
    - name: Setup R
      steps:
        uses: r-lib/actions/setup-r@v2
        with: r-version: '4.2.2'
    - run: Rscript -e 'print("hello")'



