name: R

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.2']

steps:
- uses: actions/checkout@v3
- uses: r-lib/actions/setup-r@v2
  with:
    r-version: '4.2.2'
- run: Rscript -e 'print("hello")'



